### ISSUE TITLE
Add permission to master branch only allow pull request update, and add PR to at least one approval to merge

### ISSUE THREAD

**Issue by zeyao** [stevahnes/ng-resume-builder#4]
You can refer this this notes:

https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule

Also please add me as admin so I could do the set up, I could not see a setting selection.

**Comment by stevahnes** [comment]
I set it up alr, but can't find how to add you more than just as a collaborator le.. Try again some other day?

**Comment by zeyao** [comment]
![Screenshot 2021-03-08 at 12 10 36 AM](https://user-images.githubusercontent.com/5878926/110246482-b7340000-7fa2-11eb-8ba6-caf2e0f8b6ca.png)
I guess you set up for all brunch to protected, we should set only master to protected with only PR updated. Now I could not commit to the brunch I created. 

Could you try can you commit to any brunch other than mater. Or it is only me could not?

**Comment by stevahnes** [comment]
Should be fixed!
